// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ColumnKind } from "./ColumnKind";
import type { ProfileChart } from "./ProfileChart";

/**
 * What one column holds under the grid's filter, for the panel beside the
 * grid. Computed by `services::profile::profile_column`.
 */
export type ColumnProfile = { column: string, kind: ColumnKind, 
/**
 * Rows under the filter — the count the grid's footer shows.
 */
total_rows: number, null_count: number, 
/**
 * Distinct non-null values; absent for a type the count is not
 * defined on (nested, interval).
 */
distinct_count: number | null, chart: ProfileChart, };
