// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ColumnKind } from "./ColumnKind";

export type ColumnInfo = { name: string, column_type: string, kind: ColumnKind, logical_type: string | null, physical_type: string, };
