// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ColumnKind } from "./ColumnKind";

/**
 * What one column holds under the grid's filter, in the numbers the panel
 * shows above its chart. The first of the two answers a profile is made of
 * (`services::profile`): they arrive separately because the counts take a
 * scan and the chart takes another, and on a large file the panel would
 * otherwise show nothing until both were done. The chart is chosen from
 * these counts, so the second call is given them back.
 */
export type ColumnCounts = { column: string, kind: ColumnKind, 
/**
 * Rows under the filter — the count the grid's footer shows.
 */
total_rows: number, null_count: number, 
/**
 * Distinct non-null values; absent for a type the count is not
 * defined on (nested, interval).
 */
distinct_count: number | null, 
/**
 * Whether `distinct_count` is an estimate. An exact count keeps every
 * distinct value in memory and cannot spill, so on a large column it
 * asks for more than the session's memory pool has; the profile then
 * estimates rather than failing, and says so here — a number the panel
 * prints unqualified would be read as the count it is not.
 */
distinct_approximate: boolean, };
