// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a column structurally is, independent of how its type is labelled.
 * The filter bar decides quoting from this; the display strings
 * (`column_type` etc.) are free to change wording without affecting it.
 */
export type ColumnKind = "boolean" | "integer" | "float" | "decimal" | "text" | "temporal" | "binary" | "nested" | "other";
