// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One row of a directory listing. `size` is set for files, `children`
 * only by the webview once it has listed the directory itself.
 */
export type FileEntry = { path: string, name: string, is_directory: boolean, is_parquet: boolean, size?: number | null, children?: Array<FileEntry> | null, };
