// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One bucket of a histogram: `lower <= value < upper`. Both ends are SQL
 * literals a filter on the column accepts as typed — bare numbers, or a
 * date / time / timestamp in the text arrow renders it with — so a click on
 * the bucket becomes `col >= lower AND col < upper` without another
 * rendering step.
 */
export type HistogramBucket = { lower: string, upper: string, count: number, };
