// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One bucket: `lower <= value < upper`, or `<= upper` when
 * `upper_inclusive` is set. Both ends are SQL
 * literals a filter on the column accepts as typed — bare numbers, or a
 * date / time / timestamp in the text arrow renders it with — so a click on
 * the bucket becomes a pair of comparisons without another
 * rendering step. The last time-of-day bucket uses an inclusive upper
 * bound at the final representable instant of the day.
 */
export type HistogramBucket = { lower: string, upper: string, upper_inclusive: boolean, count: number, };
