// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The role of a store product, so the webview never carries a product id.
 */
export type IapProductKind = "trial" | "full";
