// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IapPurchaseOutcome } from "./IapPurchaseOutcome";
import type { IapStatus } from "./IapStatus";

export type IapPurchaseResult = { outcome: IapPurchaseOutcome, 
/**
 * The status after the purchase was accounted for.
 */
status: IapStatus, };
