// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A product as the App Store describes it in the user's storefront —
 * name, description and price are App Store Connect's, not the app's.
 * The webview buys by the `id` it got from here and carries none of its own.
 */
export type IapProduct = { id: string, display_name: string, description: string, 
/**
 * Localized, currency included (`¥1,500`, `$9.99`).
 */
display_price: string, };
