// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IapProductKind } from "./IapProductKind";

/**
 * A product as the App Store describes it in the user's storefront —
 * name, description and price are App Store Connect's, not the app's.
 */
export type IapProduct = { id: string, kind: IapProductKind, display_name: string, description: string, 
/**
 * Localized, currency included (`¥1,500`, `$9.99`).
 */
display_price: string, };
