// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where the app stands with the trial and the one-time purchase; derived
 * by `services::store::License` from the App Store entitlements and the
 * clock, never stored by the webview.
 */
export type IapState = "none" | "trial" | "trial_expired" | "unlocked";
