// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether the one-time purchase is owned; derived by
 * `services::store::License` from the App Store entitlements, never
 * stored by the webview. The free tier's limits are the webview's
 * business (see `features/license/lib/license.ts`); the backend only
 * answers "is the full version owned".
 */
export type IapState = "free" | "unlocked";
