// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IapState } from "./IapState";

export type IapStatus = { state: IapState, 
/**
 * Unix time in milliseconds when the trial ends (or ended), once one
 * was started; the banner and the paywall count down from it.
 */
trial_ends_at: number | null, 
/**
 * The trial length the backend enforces, so the screens quote the
 * same number.
 */
trial_days: number, 
/**
 * Set when the entitlements could not be read from the App Store;
 * the app is locked until they can be.
 */
store_error: string | null, };
