// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ColumnInfo } from "./ColumnInfo";

export type ParquetMetadata = { num_rows: number, num_columns: number, columns: Array<ColumnInfo>, };
