// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HistogramBucket } from "./HistogramBucket";
import type { ValueCount } from "./ValueCount";

/**
 * The chart a column profile carries; which one is
 * `services::profile`'s decision.
 */
export type ProfileChart = { "shape": "top_values", values: Array<ValueCount>, other: number, } | { "shape": "histogram", buckets: Array<HistogramBucket>, other: number, } | { "shape": "unsupported" };
