// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QueryChartType } from "./QueryChartType";

/**
 * One column of a SQL result: the name the query gave it and its Arrow type
 * rendered for display. Not `ColumnInfo` — that describes a column of the
 * parquet file itself, and a query's columns can be computed, joined or
 * aggregated, where a physical or logical parquet type means nothing.
 */
export type QueryColumn = { name: string, data_type: string, chart_type: QueryChartType, };
