// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QueryColumn } from "./QueryColumn";

export type QueryResult = { columns: Array<QueryColumn>, 
/**
 * One JSON object per row, already rendered webview-safe by
 * `batches_to_rows` (decimals and big integers as strings).
 */
rows: Record<string, unknown>[], execution_time_ms: number, 
/**
 * True when the result was cut at `max_rows`.
 */
truncated: boolean, max_rows: number, };
