// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a SQL result column can be on a chart, decided from the result's
 * Arrow schema. The webview cannot decide this itself: `data_type` is the
 * type's display string, which is free to change wording, and the file's
 * `ColumnInfo` describes the file, not a query — `CAST`, arithmetic and
 * aggregates all change the type. Only the two things a chart needs are
 * distinguished: how to parse the values (`batches_to_rows` renders
 * decimals and big integers as strings) and whether the column is a
 * continuous axis.
 *
 * Dictionary-encoded columns are `unsupported` rather than mapped to their
 * value type: the JSON rendering of a dictionary's decimals and non-finite
 * floats is not tested to match a plain column's, so the webview would be
 * parsing values it cannot trust. A `CAST` in the query unwraps them.
 */
export type QueryChartType = { "kind": "integer" } | { "kind": "float" } | { "kind": "decimal" } | { "kind": "date" } | { "kind": "timestamp", 
/**
 * Arrow's timezone string, `None` for a wall-clock timestamp.
 */
timezone: string | null, } | { "kind": "category" } | { "kind": "unsupported" };
