// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One Recent Files entry.
 */
export type RecentFile = { path: string, name: string, size: number, 
/**
 * Unix time in milliseconds; the webview formats it.
 */
last_accessed: number, 
/**
 * False when the file cannot be reached any more (deleted, or the
 * bookmark no longer resolves); the list shows it greyed out.
 */
available: boolean, };
