// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionTabState } from "./SessionTabState";

/**
 * What the webview sends to `save_session` for each open tab.
 */
export type SessionTabInput = { path: string, state: SessionTabState, };
