// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionTabState } from "./SessionTabState";

/**
 * A tab from the last session, as the webview reopens it at launch.
 */
export type SessionTab = { path: string, name: string, state: SessionTabState, 
/**
 * False when the file cannot be reached any more (deleted, or the
 * bookmark no longer resolves); the webview skips it and says so.
 */
available: boolean, };
