// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The part of a tab's view state worth restoring after a relaunch. Every
 * field is optional: the webview sends what the tab has set, and reads
 * back what was saved with the tab's own defaults for the rest.
 */
export type SessionTabState = { 
/**
 * `browse` or `query`.
 */
view_mode: string | null, 
/**
 * 1-based page of the browse grid.
 */
current_page: number | null, 
/**
 * The SQL `WHERE` fragment the browse grid applies.
 */
active_filter: string | null, };
