// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionTab } from "./SessionTab";

/**
 * The tabs of the last session, in their order, and the active one's path.
 */
export type SessionTabs = { tabs: Array<SessionTab>, active: string | null, };
