// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SortDirection } from "./SortDirection";

/**
 * The order the browse grid shows its rows in: one column, ascending or
 * descending. What the header's sort button sets, and what a page read
 * and an export carry so they walk the same sequence. `None` anywhere a
 * sort is optional means file order.
 */
export type SortSpec = { column: string, direction: SortDirection, };
