// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One value of a column and how many rows hold it.
 */
export type ValueCount = { 
/**
 * Rendered like a grid cell (`batches_to_rows`), so the webview shows
 * it as the grid does and can type it back into a filter as it is.
 */
value: unknown, count: number, };
