// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A folder the user opened as a workspace root.
 */
export type WorkspaceRoot = { path: string, name: string, };
